config/routes.rb
PmaApp::Application.routes.draw do
  root to: 'static_pages#home'

  resources :users
  resources :events
  resources :quotes do
    resources :items
  end
  resources :items
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/home', to: 'static_pages#home'
  match '/about', to: 'static_pages#about'

  get "events/show"

  get "static_pages/home"

  get "static_pages/about"

  get "welcome/hiu"

  get "items/new"

  get "quotes/new"

  get "events/new"

  get "items/new"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

  	if user.admin?
  		can :manage, :all
  	elsif user.nil?
  		can :read, :all
  		can :manage, User, id => user.id
  	else
  		can :read, :all
  	end

  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :date, :location, :name, :user_id

  validates :date, presence: true
  validates :name, presence: true
  validates :location, presence: true
  validates :user_id, :presence => { :message => "user_id is required" }
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :name, :qty, :cost, :quote_id

  belongs_to :quote
  # accepts_nested_attributes_for :quote

  validates :name, presence: true
  validates :qty, presence: true
  validates :cost, presence: true
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  attr_accessible :date, :email, :phone, :item_ids

  has_many :items
  accepts_nested_attributes_for :items, :reject_if => lambda { |a| a[:id].blank? }

  validates :date, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX }
  VALID_PHONE_REGEX = /[0-9]/i
  validates :phone, presence:   true,
                    format:     { with: VALID_PHONE_REGEX },
                    length: { is: 10 }
  # validates :cost, presence: true
end

app/models/request.rb
class Request < ActiveRecord::Base
  attr_accessible :date, :email, :phone

  has_many :requested_items, dependent: :destroy

  validates :date, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX }
  VALID_PHONE_REGEX = /[0-9]/i
  validates :phone, presence:   true,
                    format:     { with: VALID_PHONE_REGEX },
                    length: { is: 10 }
end

app/models/requested_items.rb
class RequestedItems < ActiveRecord::Base
  attr_accessible :item_id, :qty, :quote_id
  belongs_to :item
  belongs_to :request


end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation, :info
  has_secure_password

  has_many :events

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end 
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :admin_user,     only: [:destroy, :new, :update]

  def new
  	@event = Event.new
  end

  def create
    @event = current_user.events.build(params[:event])
    if @event.save
      flash[:success] = "Event Added."
      redirect_to events_path
    else
      render 'new'
    end 
  end

  def update
    @event.update_attributes(params[:event])
  end

  def destroy
    Event.find(params[:id]).destroy
    flash[:success] = "Event destroyed."
    redirect_to events_path
  end 

  def show
     @event = Event.find(params[:id])
  end

  def index
  	@events = Event.paginate(page: params[:page])
  end

  private
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end 
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_filter :admin_user,     only: [:destroy, :new]

  def new
  	@item = Item.new
  end

  def create
    @item = Item.new(params[:item])
    if @item.save
      flash[:success] = "Item Added."
      redirect_to items_path
    else
      render 'new/item'
    end 
  end

  def destroy
    Item.find(params[:id]).destroy
    flash[:success] = "Item destroyed."
    redirect_to items_path
  end 

  def index
  	@items = Item.paginate(page: params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  private
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end 
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def new
    # @items = Item.all
  	@quote = Quote.new
  end

  def create
    @quote = Quote.create(params[:quote])
    if @quote.save
      flash[:success] = "Quote sent to Admin."
      # begin
        QuoteMailer.quote_email(@quote).deliver
      # rescue
      #   puts "***!!!Mail not sent!!!***"
      # end
      redirect_to new_quote_path
    else
      flash[:fail] = "Quote incorrect."
      redirect_to new_quote_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
    	user = User.find_by_email(params[:session][:email])
    	if user && user.authenticate(params[:session][:password])
    		sign_in user
      	redirect_to user
    	else
      		flash.now[:error] = 'Invalid email/password combination'
      		render 'new'
    	end
  	end 

  def destroy
    sign_out
    redirect_to root_path
  end 
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: [:destroy, :new]

  def new
  	@user = User.new
  end

  def show
    @user = User.find(params[:id])
  end 

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Member Added."
      redirect_to signup_path
    else
      render 'new'
    end 
  end 

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end 

  def index
    @users = User.paginate(page: params[:page])
  end

  def edit
  end 

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end 

  private
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end 

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
   cookies.permanent[:remember_token] = user.remember_token
   self.current_user = user
 end

 def signed_in?
   !current_user.nil?
 end 

 def current_user=(user)
   @current_user = user
 end 

 def current_user
  @current_user ||= User.find_by_remember_token(cookies[:remember_token])
end 

def sign_out
  self.current_user = nil
  cookies.delete(:remember_token)
end 

def current_user?(user)
  user == current_user
end 

def admin?
	@current_user.admin?
end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id} .png?s=
                        #{size} "
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end 

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.sinfonia.org/">Phi Mu Alpha</a>
    by David Corpstein
  </small>
</footer> 

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Eta Nu", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li> <%= link_to "Home",    root_path %> </li>
          <li> <%= link_to "About Us",    about_path %> </li>
          <li> <%= link_to "Events", events_path %> </li>
          <li> <%= link_to "Equipment Rental", items_path %> </li>
          <li> <%= link_to "Users", users_path %> </li>
          <li> <%= link_to "Quote", new_quote_path %> </li>
          <% if signed_in? %>
            <% if admin? %>
              <li><%= link_to "Add Member", signup_path %></li>
              <li><%= link_to "Add Event", new_event_path %></li>
              <li><%= link_to "Add Item", new_item_path %></li>
            <% end %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li> <%= link_to "Profile", current_user %> </li>
                <li> <%= link_to "Settings", edit_user_path(current_user) %> </li> 
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else   %>
            <li> <%= link_to "Sign in", signin_path %> </li>
          <% end  %> 
        </ul>
      </nav>
    </div>
  </div>
</header> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <link rel="shortcut icon" href="http://campus.albion.edu/phimualpha/files/2010/04/shapeimage_2.jpg">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %> 
	<div class="container" style="background-color:black">
    <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> "> <%= value %> </div>
    <% end %> 
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %> 
  </div> 

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %> </li>
    <% end %>
    </ul>
  </div>
<% end %> 